export const productsData = [
  {
    quantity: 1,
    availableSize:['x','l','m'],
    id: 1,
    title: "Watch",
    price: 100,
    imageUrl: "./assest/image/p1.jpg",
    all: 100,
    cat: "Jevelry",
  },
  {
    quantity: 1,
    availableSize:['x','l'],
    id: 2,
    title: "Shirt",
    price: 150,
    imageUrl: "./assest/image/p2.jpg",
    all: 100,
    cat: "Gwon",
  },
  {
    quantity: 1,
    availableSize:['l','m'],
    id: 3,
    title: "Gwon",
    price: 140,
    imageUrl: "./assest/image/p3.jpg",
    all: 100,
    cat: "shirt",
  },
  {
    quantity: 1,
    availableSize:['xl','m'],
    id: 4,
    title: "Jevelry",
    price: 120,
    imageUrl: "./assest/image/p4.jpg",
    cat: "x",
    all: 100,
  },
  {
    quantity: 1,
    availableSize:['2xl','l','s'],
    id: 5,
    title: "Jevelry",
    price: 150,
    imageUrl: "./assest/image/p5.jpg",
    cat: "x",
    all: 100,
  },
  {
    quantity: 1,
    availableSize:['xl','s','l'],
    id: 6,
    title: "Gwon",
    price: 160,
    imageUrl: "./assest/image/p6.jpg",
    cat: "x",
    all: 100,
  },
  {
    quantity: 1,
    availableSize:['m','2xl','x'],
    id: 7,
    title: "Gwon4",
    price: 128,
    imageUrl: "./assest/image/p6.jpg",
    cat: "x",
    all: 100,
  },
  {
    quantity: 1,
    availableSize:['xl','l','2xl'],
    id: 8,
    title: "Gwon2",
    price: 200,
    imageUrl: "./assest/image/p6.jpg",
    cat: "x",
    all: 100,
  },
  {
    quantity: 1,
    availableSize:['s','m'],
    id: 9,
    title: "Gwon3",
    price: 190,
    imageUrl: "./assest/image/p6.jpg",
    cat: "x",
    all: 100,
  },
];
